# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12f4731aba146c816e7219dc265e9687f0d0d60d3d6e5614d1d98dd4e591e024d81cf284cbe2a51ae2715ec0dc756739cc0fbae5b2634d64c2a9bc82f8b06451

test:
  secret_key_base: f75765abea33b617848390857c3fff12d30a922bc09d0624f0503a225ef678e72ed540729713f433f17f1d17c6803cb643ef572dab95c489ff11b629fb948cb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
